Controllers/SachController.cs
using BanSachOnline.Models;
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BanSachOnline.Controllers
{
    [HandleError]
    public class SachController : Controller
    {
        // GET: Sach
        QL_BanSachDataContext db = new QL_BanSachDataContext();
        public ActionResult ShowAll(int? page)
        {
            if (page == null) page = 1;
            var lstSach = db.SACHes.ToList();
            int pageSize = 10;
            int pageNumber = (page ?? 1);

            return View(lstSach.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult ChiTietSach(int ma)
        {
            SACH s = db.SACHes.SingleOrDefault(t => t.MASACH == ma);
            if (s == null)
            {
                return HttpNotFound();
            }
            return PartialView(s);
        }
        public ActionResult LoaiSach()
        {
            var lst = db.THELOAIs.OrderBy(t => t.TENTL);
            return PartialView(lst);

        }
        public ActionResult SachTheoCD(int MaLoai)
        {
            var listSach = db.SACHes.Where(s => s.MATL == MaLoai).ToList();

            if (listSach.Count == 0)
            {
                ViewBag.TB = "Không có sách thuộc chủ  đề này!";
            }
            else
            {
                string ten = db.THELOAIs.Single(t => t.MATL == MaLoai).TENTL;
                ViewBag.TenTheLoai = ten;
            }
            return PartialView(listSach);
        }

        public ActionResult TimKiemSach(string txt_search)
        {
            var lisTimKiem = (from tk in db.SACHes where tk.TENSACH.Contains(txt_search) select tk).ToList();
            if (lisTimKiem.Count == 0)
            {
                ViewBag.kqTK = string.Format("Không Tìm Thấy {0} !!!", txt_search);
            }
            ViewBag.TuKHoa = txt_search;
            return PartialView(lisTimKiem);
        }
        public ActionResult SortSach_Gia()
        {
            var lisTimKiem = db.SACHes.OrderBy(s => s.DONGIABAN).ToList();
            return PartialView(lisTimKiem);
        }
        ///// -------------------------------------------------------------------------------------------------

    }
}

Controllers/TacGiaController.cs
using BanSachOnline.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BanSachOnline.Controllers
{
    [HandleError]
    public class TacGiaController : Controller
    {
        QL_BanSachDataContext db = new QL_BanSachDataContext();
        // GET: TacGia
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult TacGia()
        {
            var lstTacGia = db.TACGIAs.ToList();
            return View(lstTacGia);
        }

        public ActionResult SachTheoTacGia(int MaTG)
        {
            List<SACH> listSachTheoTacGia = db.SACHes.Where(t => t.MATG == MaTG).ToList();
            if (listSachTheoTacGia.Count == 0)
            {
                ViewBag.TB = "Không có sách nào thuộc tác giả này !";
            }
            else
            {
                string ten = db.TACGIAs.Single(t => t.MATG == MaTG).TENTG;
                ViewBag.TenTacGia = ten;
            }
            return View(listSachTheoTacGia);
        }

        public ActionResult ShowTacGia()
        {
            var lstTacGia = db.TACGIAs.ToList();
            return View(lstTacGia);
        }
    }
}

Views/TacGia/SachTheoTacGia.cshtml
@model IEnumerable<BanSachOnline.Models.SACH>

@{
    ViewBag.Title = "SachTheoTacGia";
    Layout = "~/Views/Shared/User_LayoutPage.cshtml";
}

<div class="container text-justify row">

    <div class="text-left">
        <br />
        <h3 style="font-size:15px;"><i class="fa fa-check" aria-hidden="true"></i> Kết quả dành cho @ViewBag.TenTacGia</h3>
        <br />
    </div>

</div>
<div class="row ">
    @{
        foreach (var item in Model)
        {
        <div class="col-lg-6 bg-light border border-white">
            <div class="p-3 ">
                <div class="row g-0">
                    <div class="col-md-4">
                        <a href="@Url.Action("ChiTietSach", "Sach", new { @ma = item.MASACH },  null)">
                            <img src="~/DULIEU/Images/@item.HINHANH" id="img_giua" alt="...">
                        </a>
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <a href="@Url.Action("ChiTietSach", "Sach", new { @ma = item.MASACH }, null)">
                                <h5 class="card-title">
                                    @if (item.TENSACH.Length > 25)
                                    {
                                        <p>
                                            <strong title="@item.TENSACH">@Html.Raw(@item.TENSACH.Substring(0, 25))...</strong> <br />
                                        </p>
                                    }
                                    else
                                    {
                                        <p>
                                            <strong title="@item.TENSACH"> @Html.Raw(@item.TENSACH)</strong> <br />
                                        </p>
                                        <div class="clear"></div>
                                    }

                                </h5>
                            </a>
                            <p class="card-text">
                                @if (item.MOTA.Length > 60)
                                {
                                    <strong title="@item.MOTA">Mô tả: @Html.Raw(@item.MOTA.Substring(0, 60))...</strong> <br />
                                }
                                else
                                {
                                    <strong title="@item.MOTA">Mô tả: @Html.Raw(@item.MOTA)</strong> <br />
                                    <div class="clear"></div>
                                }

                            </p>
                            <p class="card-text text-red">Giá: @string.Format("{0:0,0 VND}", @item.DONGIABAN)</p>
                            <div class="btn btn-outline-info">
                                <a href="@Url.Action("ThemGioHang","GioHang",new { @ma = item.MASACH, sl=1 , strURL=Request.Url })">
                                    <i class="fa fa-cart-plus" aria-hidden="true"></i> Thêm Vào Giỏ Hàng
                                </a>
                            </div>


                        </div>
                    </div>
                </div>
            </div>
            <div style="height:20px"></div>
        </div>

        }
    }
</div>

Views/TacGia/ShowTacGia.cshtml
@model IEnumerable<BanSachOnline.Models.TACGIA>

@{
    ViewBag.Title = "Hiện Thị Tác Giả";
    Layout = "~/Views/Shared/User_LayoutPage.cshtml";
}
<style>
    a {
        color: black;
    }
    a:hover{
        color:red;
    }
</style>
<div class="p-3 bg-light">

    <div class="container text-justify row">

        <div class="text-left">
            <br />
            <h3 style="font-size:15px;"><i class="fa fa-check" aria-hidden="true"></i> Tác giả !</h3>
            <br />
        </div>

    </div>
    <div class="row">
        @foreach (var item in Model)
        {
            <div class="col-lg-4 border border-white p-1" style="color:red">
                <i class="fa fa-user-o" aria-hidden="true"></i>
                @if (item.TENTG.Length > 30)
                {
                    <strong title="@item.TENTG"> @Html.ActionLink(@item.TENTG.Substring(0, 30), "SachTheoTacGia", "TacGia", new { MaTG = item.MATG }, null)</strong>
                }
                else
                {
                    <strong title="@item.TENTG"> @Html.ActionLink(@item.TENTG, "SachTheoTacGia", "TacGia", new { MaTG = item.MATG }, null)</strong>
                }
            </div>
        }
    </div>
    <div style="height:30px"></div>
</div>

Views/TacGia/TacGia.cshtml
@model IEnumerable<BanSachOnline.Models.TACGIA>


<ul class="dropdown">
    @foreach (var item in Model)
    {
        <li class="border">
            @Html.ActionLink(@item.TENTG, "SachTheoTacGia", "TacGia", new { MaTG = item.MATG }, null)

        </li>
    }
</ul>